// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szwtiuuwnthtktjgxuzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6d3RpdXV3bnRodGt0amd4dXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTk4MjEsImV4cCI6MjA3MTU5NTgyMX0.BvGNQpzC96i1kKZongdc8_Lj_PI630WO_Fr62XA_kos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});